"""Mudando tamanho do campo email

Revision ID: cbeb7655d6d2
Revises: d8ef4bed783a
Create Date: 2024-06-24 23:53:16.386836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbeb7655d6d2'
down_revision: Union[str, None] = 'd8ef4bed783a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.alter_column('email',
                existing_type=sa.VARCHAR(length=100),
                type_=sa.String(length=125),
                existing_nullable=False)
    with op.batch_alter_table('pessoa2', schema=None) as batch_op:
        batch_op.alter_column('email',
                existing_type=sa.VARCHAR(length=100),
                type_=sa.String(length=125),
                existing_nullable=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('pessoa', schema=None) as batch_op:
        # ### commands auto generated by Alembic - please adjust! ###
        batch_op.alter_column('email',
                existing_type=sa.String(length=125),
                type_=sa.VARCHAR(length=100),
                existing_nullable=False)
    with op.batch_alter_table('pessoa2', schema=None) as batch_op:
        batch_op.alter_column('email',
                existing_type=sa.String(length=125),
                type_=sa.VARCHAR(length=100),
                existing_nullable=False)
        # ### end Alembic commands ###
